version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  foodgram_backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/static
      - media:/media
  copy_static:
    image: busybox
    volumes:
      - ./frontend/build:/from
      - static:/to
    command: cp -r /from/. /to
  foodgram_gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static/
      - media:/media/
