version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  foodgram_backend:
    image: frailtynine/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db
  foodgram_gateway:
    image: frailtynine/kittygram_gateway:latest
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - db
      - foodgram_backend
