# Generated by Django 3.2.3 on 2023-12-11 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_recipe',
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('name', 'text', 'author', 'cooking_time')},
        ),
    ]
