# Generated by Django 3.2.3 on 2023-11-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20231122_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoriterecipe',
            name='is_in_shopping_cart',
            field=models.BooleanField(default=False),
        ),
    ]
