# Generated by Django 3.2.3 on 2023-12-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20231211_2114'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipefavorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_recipefavorite'),
        ),
        migrations.AddConstraint(
            model_name='recipeinshoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_recipeinshoppingcart'),
        ),
    ]
