# Generated by Django 3.2.3 on 2023-12-11 21:23

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20231211_2118'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.CheckConstraint(check=models.Q(('user_follows', django.db.models.expressions.F('user_following')), _negated=True), name='no_self_following'),
        ),
    ]
