# Generated by Django 3.2.3 on 2023-12-11 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_userfollowing_no_self_following'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfollowing',
            name='no_self_following',
        ),
    ]
